# Generated by Django 6.0.6 on 2026-06-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Yili')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Janri')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('telegram_file_id', models.CharField(max_length=255, unique=True, verbose_name='Telegram file_id')),
                ('telegram_message_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
                'ordering': ['-created_at'],
            },
        ),
    ]
