# Generated by Django 6.0.6 on 2026-06-25 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Actors')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rejissors/')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Yili')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Janr')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='categories/')),
            ],
        ),
        migrations.CreateModel(
            name='Rejissor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Actors')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='rejissors/')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Yili')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Yili')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='posters/')),
                ('telegram_file_id', models.CharField(max_length=255, unique=True, verbose_name='Telegram file_id')),
                ('telegram_message_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.actor', verbose_name='Actors')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category', verbose_name='Janr')),
                ('last_episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.movie')),
                ('rejissor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.rejissor', verbose_name='Rejissor')),
            ],
            options={
                'verbose_name': 'Kino',
                'verbose_name_plural': 'Kinolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name="Tug'ri")),
                ('name', models.CharField(max_length=100, verbose_name='Ismi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie', verbose_name='Kino')),
            ],
        ),
    ]
